//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatrixGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatrixGenerator.Resources.TaskResources", typeof(TaskResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дана квадратная матрица. Необходимо определить количество четных элементов..
        /// </summary>
        internal static string EvenCount {
            get {
                return ResourceManager.GetString("EvenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дана квадратная матрица. Необходимо определить количество четных элементов в четных столбцах..
        /// </summary>
        internal static string EvenCountEvenColumns {
            get {
                return ResourceManager.GetString("EvenCountEvenColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дана квадратная матрица. Необходимо определить количество четных элементов в четных строках..
        /// </summary>
        internal static string EvenCountEvenRows {
            get {
                return ResourceManager.GetString("EvenCountEvenRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дана квадратная матрица. Необходимо определить количество четных элементов в нечетных столбцах..
        /// </summary>
        internal static string EvenCountOddColumns {
            get {
                return ResourceManager.GetString("EvenCountOddColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дана квадратная матрица. Необходимо определить количество четных элементов в нечетных строках..
        /// </summary>
        internal static string EvenCountOddRows {
            get {
                return ResourceManager.GetString("EvenCountOddRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дана квадратная матрица. Необходимо определить сумму элементов расположенных на главной диагонали..
        /// </summary>
        internal static string MainDiagonalSum {
            get {
                return ResourceManager.GetString("MainDiagonalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дана квадратная матрица. Необходимо определить скалярное произведение векторов, координаты которых расположены в строках матрицы..
        /// </summary>
        internal static string Scalar {
            get {
                return ResourceManager.GetString("Scalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дана квадратная матрица. Необходимо определить сумму элементов расположенных на побочной диагонали..
        /// </summary>
        internal static string SideDiagonalSum {
            get {
                return ResourceManager.GetString("SideDiagonalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дана квадратная матрица. Необходимо определить сумму элементов в указанном строке..
        /// </summary>
        internal static string SumXRow {
            get {
                return ResourceManager.GetString("SumXRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дана квадратная матрица. Необходимо определить сумму элементов в указанном столбце..
        /// </summary>
        internal static string SumYColumn {
            get {
                return ResourceManager.GetString("SumYColumn", resourceCulture);
            }
        }
    }
}
