namespace MatrixGenerator
{
    enum TaskType
    {
        BytesEvenCount,
        BytesLess3,
        EvenCount,
        EvenCountEvenColumns,
        EvenCountEvenRows,
        EvenCountOddColumns,
        EvenCountOddRows,
        MainDiagonalSum,
        MinMainDiagonal,
        MinSideDiagonal,
        Mul3Unmul2,
        Mul3Unmul5,
        MulEvenDiagonalNumbers,
        MulMainAndSideDiagonal,
        MulOddDiagonalNumbers,
        MulPrimeDiagonalNumbers,
        MulSumEvenSumOdd,
        NumberRowMinSum,
        OddCount,
        PrimeNumberCount,
        Scalar,
        SideDiagonalSum,
        SumIndexMaxNumber,
        SumIndexMinNumber,
        SumMaxInColumn,
        SumMaxInRow,
        SumMinInColumn,
        SumMinInRow,
        SumMul4Unmul6,
        SumPrimeNumbers
    }
}
